/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import DAO.DBconnection;
//import static Mahoa.DES_Encrypt.Des_encrypt;
//import static Mahoa.MD5.md5;

//import static Mahoa.RSA.rsa_encrypt;
//import static Mahoa.RSA.rsa_encrypt1;
//import static Mahoa.RSA1.rsa1;
import static DAO.RSA.rsa_encrypt;
import static DAO.RSA.rsa_encrypt1;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import DAO.DBconnection;
import static DAO.DES_Encrypt.Des_encrypt;
import static DAO.RSA.encrypt;
import static DAO.RSA.generatePublicKey;
import java.security.PublicKey;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author HUNG
 */
public class frmDangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public frmDangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_dn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jText_tk = new javax.swing.JTextField();
        jPassword_mk = new javax.swing.JPasswordField();
        jButton_dk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_dn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_dn.setText("Đăng nhập");
        jButton_dn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nhập tài khoản");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nhập mật khẩu");

        jText_tk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPassword_mk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton_dk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_dk.setText("Đăng ký");
        jButton_dk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dkActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 11, 11));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        jLabel4.setText("Quản lý Cửa hàng Vật liệu xây dựng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPassword_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_dn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_dk, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jText_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton_dn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_dk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_dnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dnActionPerformed
        // TODO add your handling code here:
        String tk = this.jText_tk.getText();
        String mk = String.valueOf(this.jPassword_mk.getPassword());
        //String mk = this.jPassword_mk.getText();
        if(tk.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền tài khoản !");
        }
        else if(mk.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền mật khẩu !");
        }
        else{
             try{

           mk = Des_encrypt(mk);
           Connection conn = null;
           String strconn = "jdbc:oracle:thin:@192.168.56.1:1521:orcl";
//            conn = DriverManager.getConnection(strconn,"hr","hr");
            Connection connection=DBconnection.getConnection();
            String query="SELECT * FROM NGUOIDUNG WHERE TAIKHOAN LIKE ? AND MATKHAU LIKE ?" ;
            PreparedStatement ps=connection.prepareStatement(query);
            ps.setString(1,tk);
            ps.setString(2,mk);
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                int ok = JOptionPane.showConfirmDialog(null, "Đăng nhập thành công",
                        null, JOptionPane.YES_NO_OPTION);
                if (ok == JOptionPane.YES_OPTION) {
                   new frmDanhMuc().setVisible(true);
                    this.hide();
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Đăng nhập thất bại do sai tên tài khoản hoặc mật khẩu");
            }
        }catch(SQLException e){
            Logger.getLogger(frmDanhMuc.class.getName()).log(Level.SEVERE,null,e);
             JOptionPane.showMessageDialog(null,"Lỗi kết nối !!!!");
            } catch (Exception ex) {
                Logger.getLogger(frmDangNhap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_dnActionPerformed

    private void jButton_dkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dkActionPerformed
        // TODO add your handling code here:
        new frmDangKyDES().setVisible(true);
                    this.hide();
    }//GEN-LAST:event_jButton_dkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_dk;
    private javax.swing.JButton jButton_dn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPassword_mk;
    private javax.swing.JTextField jText_tk;
    // End of variables declaration//GEN-END:variables
}
