/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.HoaDonBanDAO;
import POJO.HoaDonBanPOJO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class frmHoaDonBan extends javax.swing.JFrame {

    /**
     * Creates new form frmHoaDonBan
     */
    public frmHoaDonBan() {
        initComponents();
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMahd = new javax.swing.JTextField();
        txtManv = new javax.swing.JTextField();
        txtMamh = new javax.swing.JTextField();
        txtTenmh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        txtNgayban = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDongia = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_qlhd = new javax.swing.JTable();
        btnTimkiem = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        btnLammoi = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnChitiet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hoá đơn bán");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 5, 5));
        jLabel1.setText("Quản lý hoá đơn bán");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã hoá đơn:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mã nhân viên:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mã mặt hàng:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tên mặt hàng:");

        txtMahd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtManv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtMamh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtTenmh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Số lượng:");

        txtSoluong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtNgayban.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Ngày bán:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tổng tiền:");

        txtTongtien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Đơn giá:");

        txtDongia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/repair.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tbl_qlhd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbl_qlhd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_qlhd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_qlhdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_qlhd);

        btnTimkiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        txtTim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnLammoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new.png"))); // NOI18N
        btnLammoi.setText("Làm mới");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/real-estate.png"))); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnChitiet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChitiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/receipt.png"))); // NOI18N
        btnChitiet.setText("Xem chi tiết");
        btnChitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChitietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(btnTimkiem)
                                .addGap(18, 18, 18)
                                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLammoi)))
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMahd)
                                    .addComponent(txtManv)
                                    .addComponent(txtMamh)
                                    .addComponent(txtTenmh, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoluong)
                                    .addComponent(txtNgayban)
                                    .addComponent(txtTongtien)
                                    .addComponent(txtDongia)))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBack)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addGap(18, 18, 18)
                .addComponent(btnChitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMahd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDongia)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMamh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenmh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayban, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChitiet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnXoa)
                        .addComponent(btnSua)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimkiem)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLammoi))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadDataToTable() {
        HoaDonBanDAO p = new HoaDonBanDAO();
        ArrayList<HoaDonBanPOJO> ds = p.dsHD();

        DefaultTableModel model = (DefaultTableModel) tbl_qlhd.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"Mã hoá đơn", "Mã nhân viên", "Mã mặt hàng", "Tên mặt hàng", "Số lượng", "Đơn giá", "Tổng tiền", "Ngày bán"});
        for (HoaDonBanPOJO hd : ds) {
            Object[] row = new Object[]{hd.mahd, hd.manv, hd.mamh, hd.tenmh, hd.soluong, hd.dongia, hd.tongtien, hd.ngayban};
            model.addRow(row);
        }
    }

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (this.txtMahd.getText().length() == 0)
            JOptionPane.showMessageDialog(null, "Mã hoá đơn không thể bỏ trống!", "thông báo", 2);
        else if (this.txtMahd.getText().length() > 10)
            JOptionPane.showMessageDialog(null, "Mã hoá đơn không được lớn hơn 5 ký tự!", "thông báo", 2);
        else {
            xoa();
            loadDataToTable();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        frmDanhMuc frm = new frmDanhMuc();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (this.txtMahd.getText().length() == 0)
            JOptionPane.showMessageDialog(null, "Mã hoá đơn không thể bỏ trống!", "Thông báo", 2);
        else if (this.txtMahd.getText().length() > 5)
            JOptionPane.showMessageDialog(null, "Mã hoá đơn không được lớn hơn 5 ký tự!", "Thông báo", 2);
        else {
            them();
            loadDataToTable();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (this.txtMahd.getText().length() == 0)
            JOptionPane.showMessageDialog(null, "Mã hoá đơn không thể bỏ trống!", "Thông báo", 2);
        else if (this.txtMahd.getText().length() > 5)
            JOptionPane.showMessageDialog(null, "Mã hoá đơn không được lớn hơn 5 ký tự!", "Thông báo", 2);
        else {
            sua();
            loadDataToTable();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
        timkiem();
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:
        reset();
        this.btnThem.setEnabled(true);
        this.txtMahd.setEditable(true);
        this.txtManv.setEditable(true);
        this.txtMamh.setEditable(true);
        this.txtMahd.requestFocus();
        loadDataToTable();
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void tbl_qlhdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_qlhdMouseClicked
        // TODO add your handling code here:
        this.btnThem.setEnabled(false);
        bidingtblPB();
    }//GEN-LAST:event_tbl_qlhdMouseClicked

    private void btnChitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChitietActionPerformed
        // TODO add your handling code here:
        frmCTHoaDonBan frm = new frmCTHoaDonBan();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnChitietActionPerformed

    public void bidingtblPB() {
        HoaDonBanDAO p = new HoaDonBanDAO();
        ArrayList<HoaDonBanPOJO> ds = p.dsHD();
        int index = tbl_qlhd.getSelectedRow();
        HoaDonBanPOJO hd = ds.get(index);
        txtMahd.setText(hd.getMahd());
        this.txtMahd.setEditable(false);
        txtManv.setText(hd.getManv());
        this.txtManv.setEditable(false);
        txtMamh.setText(hd.getMamh());
        this.txtMamh.setEditable(false);
        txtTenmh.setText(hd.getTenmh());
        txtSoluong.setText(hd.getSoluong() + "");
        txtDongia.setText(hd.getDongia() + "");
        txtTongtien.setText(hd.getTongtien() + "");
        txtNgayban.setText(hd.getNgayban());
    }

    public void reset() {

        this.txtMahd.setText("");
        this.txtManv.setText("");
        this.txtMamh.setText("");
        this.txtTenmh.setText("");
        this.txtSoluong.setText("");
        this.txtDongia.setText("");
        this.txtTongtien.setText("");
        this.txtNgayban.setText("");
        this.txtTim.setText("");

    }

    public void them() {
        HoaDonBanPOJO nv = new HoaDonBanPOJO(txtMahd.getText(), txtManv.getText(), txtMamh.getText(), txtTenmh.getText(), Integer.parseInt(txtSoluong.getText()),
                Integer.parseInt(txtDongia.getText()), Integer.parseInt(txtTongtien.getText()), txtNgayban.getText());
        HoaDonBanDAO p = new HoaDonBanDAO();
        p.themHoaDonBan(nv);

    }

    public void xoa() {
        HoaDonBanDAO p = new HoaDonBanDAO();
        p.xoaHoaDonBan(txtMahd.getText());

    }

    public void sua() {
        HoaDonBanPOJO nv = new HoaDonBanPOJO(txtMahd.getText(), txtManv.getText(), txtMamh.getText(), txtTenmh.getText(), Integer.parseInt(txtSoluong.getText()),
                Integer.parseInt(txtDongia.getText()), Integer.parseInt(txtTongtien.getText()), txtNgayban.getText());
        HoaDonBanDAO p = new HoaDonBanDAO();
        p.suaHoaDonBan(nv);
    }

    public void timkiem() {
        HoaDonBanDAO p = new HoaDonBanDAO();
        ArrayList<HoaDonBanPOJO> ds = p.timKiemTheoMaHD(txtTim.getText());

        DefaultTableModel model = (DefaultTableModel) tbl_qlhd.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"Mã hoá đơn", "Mã nhân viên", "Mã mặt hàng", "Tên mặt hàng", "Số lượng", "Đơn giá", "Tổng tiền", "Ngày bán"});
        for (HoaDonBanPOJO hd : ds) {
            Object[] row = new Object[]{hd.mahd, hd.manv, hd.mamh, hd.tenmh, hd.soluong, hd.dongia, hd.tongtien, hd.ngayban};
            model.addRow(row);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHoaDonBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHoaDonBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHoaDonBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHoaDonBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHoaDonBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChitiet;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_qlhd;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtMahd;
    private javax.swing.JTextField txtMamh;
    private javax.swing.JTextField txtManv;
    private javax.swing.JTextField txtNgayban;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenmh;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txtTongtien;
    // End of variables declaration//GEN-END:variables
}
