/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.loginLogoutDAO;
import DAO.nhatkiDAO;
import POJO.nhatKiPOJO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import POJO.checkLoginPOJO;

/**
 *
 * @author Asus
 */
public class frmNhatKi extends javax.swing.JFrame {

    /**
     * Creates new form frmNhatKi
     */
    public frmNhatKi() {
        initComponents();
       // loadNhatKiToTable();
    }
    
    
        public void loadNhatKiToTable() {
        nhatkiDAO p = new nhatkiDAO();
        ArrayList<nhatKiPOJO> ds = p.dsNK();

        DefaultTableModel model = (DefaultTableModel) jblNhatKi.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"Đối tượng", "Hoạt Động", "Sự kiện", "Truy cập", "Thời gian"});
        for (nhatKiPOJO nv : ds) {
            Object[] row = new Object[]{nv.doiTuong, nv.hoatDong, nv.suKien, nv.truyCap, nv.thoiGian};
            model.addRow(row);
        }
    }
        
        public void loadNhatKiLoginToTable() {
        loginLogoutDAO p = new loginLogoutDAO();
        ArrayList<checkLoginPOJO> ds = p.dsLog();

        DefaultTableModel model = (DefaultTableModel) jblNhatKi.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"Sự kiện", "User", "Thời gian","Địa chỉ IP"});
        for (checkLoginPOJO nv : ds) {
            Object[] row = new Object[]{nv.suKien, nv.user, nv.loginLogoutTime, nv.ipAdd};
            model.addRow(row);
        }
        
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jblNhatKi = new javax.swing.JTable();
        btnXemNKTT = new javax.swing.JButton();
        btnXemlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/magnifying-glass.png"))); // NOI18N
        jLabel1.setText("   Bảng Xem Nhật Kí");

        jblNhatKi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jblNhatKi);

        btnXemNKTT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXemNKTT.setText("Xem nhật kí thay đổi dữ liệu");
        btnXemNKTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemNKTTActionPerformed(evt);
            }
        });

        btnXemlogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXemlogin.setText("Xem nhật kí đăng nhập");
        btnXemlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnXemNKTT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXemlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXemNKTT, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemNKTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemNKTTActionPerformed
        // TODO add your handling code here:
         loadNhatKiToTable();
        
    }//GEN-LAST:event_btnXemNKTTActionPerformed

    private void btnXemloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemloginActionPerformed
        // TODO add your handling code here:
       // nhatkiLogin lg = new nhatkiLogin();
       // lg.show();
       loadNhatKiLoginToTable();
    }//GEN-LAST:event_btnXemloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhatKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhatKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhatKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhatKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhatKi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXemNKTT;
    private javax.swing.JButton btnXemlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jblNhatKi;
    // End of variables declaration//GEN-END:variables
}
